package main

// /compact: trade the conversation for a summary of it. The summary is
// generated by the current target with no tools attached, seeded into a fresh
// session, and the old session stays on disk untouched — compaction is a new
// log that starts informed, never an edit to the record (§12's append-only
// posture). The optional argument steers the summary: /compact focus on the
// migration plan.

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/switchboard-code/switchboard/internal/config"
	"github.com/switchboard-code/switchboard/internal/continuity"
	"github.com/switchboard-code/switchboard/internal/prefix"
	"github.com/switchboard-code/switchboard/internal/provider"
	"github.com/switchboard-code/switchboard/internal/session"
)

const compactSystem = `You are summarizing a coding session so it can continue in a fresh context window. Write for the model that continues the work, not for a human. Capture: the task and its current state; what was tried and what failed, so nothing is repeated; decisions made and their reasons; file paths touched and what changed in each; exact commands, errors, and identifiers worth keeping; and what remains to be done, most immediate first. Plain text, no preamble, no headers about being a summary. Length proportional to what actually happened.`

const compactUsage = "usage: /compact [guidance], /compact preview, /compact auto [on|off], or /compact at <50–95>"

// compactSeedHead opens every compacted session's seed message. The session
// listings match on it to label such a session by its summary's first words
// rather than by a preamble every compacted session shares.
const compactSeedHead = "This session continues an earlier one ("

func cmdCompact(m *tuiModel, args string) tea.Cmd {
	if cmd, handled := compactSettings(m, args); handled {
		return cmd
	}
	return compactCmd(m, strings.TrimSpace(args), false)
}

// summarizerFor resolves which model writes the summary. The slots table
// wins — a summarizer slot is the statement that compaction quality should
// not depend on which rung happens to be active, and a session riding a
// small local model is exactly when that matters. Absent a binding, the
// current tier does its own summarizing, which is what it always did.
func summarizerFor(app *tuiApp) (config.Tier, bool, error) { return slotTier(app, "summarizer") }

// compactCmd is the compaction itself; auto marks the threshold-triggered
// path, whose failure handling differs in one place: a summarizer slot that
// cannot be reached fails a manual /compact outright, but the automatic path
// falls back to the current tier and says so, because it fires precisely
// when the session is about to hit the wall and stopping there would deliver
// the failure compaction exists to prevent.
func compactCmd(m *tuiModel, instructions string, auto bool) tea.Cmd {
	state := m.app.loop.Session.State()
	if len(state.Messages) == 0 {
		return noticeCmd("", "nothing to compact yet")
	}

	summarizer, fromSlot, err := summarizerFor(m.app)
	if err != nil {
		return noticeCmd("error", err.Error())
	}
	opCtx, generation, sourceID, err := m.startOperation("compact")
	if err != nil {
		return noticeCmd("warn", err.Error())
	}

	line := "compacting: summarizing " + itoa(len(state.Messages)) + " messages on " + summarizer.Target.Display()
	if fromSlot {
		line += " (the summarizer slot)"
	}
	m.addInfo(line + "…")

	app := m.app
	sourceSess := m.app.loop.Session
	return func() tea.Msg {
		// No fixed deadline: one streamed summary on a slow target can
		// legitimately outlast any cap, and a cap's only answer was killing
		// the compact at the five-minute mark. The operation stays
		// cancellable, which is the same posture a turn has.
		ctx, cancel := context.WithCancel(opCtx)
		defer cancel()
		finishNotice := func(level, text string) noticeMsg {
			return noticeMsg{level: level, text: text, operation: generation, sourceID: sourceID}
		}
		release, err := pauseAdvisorLedger(ctx, app)
		if err != nil {
			return finishNotice("error", "compact could not stabilize the session ledger: "+err.Error())
		}
		handedOff := false
		defer func() {
			if !handedOff {
				release()
			}
		}()

		client, target := app.loop.Binding().Provider, app.tier.Target
		if fromSlot {
			probed, slotClient, perr := app.providers.probeTier(ctx, summarizer)
			switch {
			case perr == nil:
				client, target = slotClient, probed.Target
			case auto:
				app.p.Send(noticeMsg{level: "warn", text: "summarizer slot " + summarizer.Target.Display() +
					" is unreachable (" + perr.Error() + "); compacting with the current tier instead"})
			default:
				return finishNotice("error", "summarizer slot "+summarizer.Target.Display()+
					" is unreachable, session unchanged: "+perr.Error())
			}
		}

		req := summarizeRequest(state.Messages, instructions)
		finish, err := beginMeteredCall(app.budget, app.catalog, sourceSess, target, req, session.UsagePurposeCompact)
		if err != nil {
			return finishNotice("error", "compact stopped before summarizing, session unchanged: "+err.Error())
		}
		summary, usage, providerDone, callErr := summarizeRequestCall(ctx, client, target, req)
		meterOutcome := callErr
		if providerDone {
			meterOutcome = nil
		}
		meterErr := finish(usage, meterOutcome)
		if err := errors.Join(callErr, meterErr); err != nil {
			return finishNotice("error", "compact failed, session unchanged: "+err.Error())
		}
		if err := ctx.Err(); err != nil {
			return finishNotice("", "")
		}

		sess, err := app.store.Create(app.workspace, app.tier.Target.ID(), app.catalog.Revision)
		if err != nil {
			return finishNotice("error", "compact failed, session unchanged: "+err.Error())
		}
		accounting := sourceSess.State()
		if err := sess.AppendBudgetTransfer("compact:"+accounting.ID, accounting.AccountedCostMicroUSD(), accounting.RetryReserveMicroUSD); err != nil {
			sess.Close()
			return finishNotice("error", "compact failed to carry the session budget, session unchanged: "+err.Error())
		}
		seed := compactSeedHead + state.ID + "). What follows is a summary of that conversation; treat it as established context.\n\n" + summary
		seedOpening := provider.UserText(seed)
		if capsule, ok := compactContinuity(accounting); ok {
			if _, err = sess.AppendContinuity(capsule); err == nil {
				seedOpening, err = stampTurnOpening(sess, seedOpening)
			}
		}
		// The acknowledgment keeps the log strictly alternating, which every
		// adapter renders correctly; a seed followed directly by the user's
		// next prompt would put two user messages back to back.
		if err == nil {
			err = sess.AppendMessage(seedOpening)
		}
		if err == nil {
			err = sess.AppendMessage(provider.Message{
				Role:    provider.RoleAssistant,
				Content: []provider.Block{provider.Text{Text: "Understood. Continuing from there."}},
			})
		}
		if err != nil {
			sess.Close()
			return finishNotice("error", "compact failed, session unchanged: "+err.Error())
		}
		handedOff = true
		return sessionSwapMsg{sess: sess, tier: app.tier, client: app.loop.Binding().Provider, fresh: false, keepFold: true, release: release,
			operation: generation, sourceID: sourceID, preserveRuntimeTarget: true,
			continuePrompt: compactContinuePrompt}
	}
}

// compactContinuePrompt opens the first turn of a compacted session. The
// summary is already established context; the instruction is to act on it,
// not to retell it.
const compactContinuePrompt = "Continue the work from the summary of the conversation so far. Pick up where it left off and keep going; do not recap the summary, act on it."

// compactContinuity carries structured task state into the compacted log.
// The generated summary already lives in the seed message, so copying it into
// Narrative would make the first provider request pay for it twice. The new
// capsule is stamped into that seed once; an explicit tombstone or a capsule
// with no useful content produces no header-only replacement.
func compactContinuity(source session.State) (continuity.Capsule, bool) {
	if source.Continuity == nil || source.Continuity.Cleared {
		return continuity.Capsule{}, false
	}

	capsule := continuity.Clone(*source.Continuity)
	// Narrative is the source context's prose summary. The new generated seed
	// supersedes it, so carrying both would duplicate context tokens. Keep the
	// explicitly structured objective/tasks/facts/decisions/files instead.
	capsule.Narrative = ""
	capsule.Omitted = withoutContinuityOmission(capsule.Omitted, "narrative")
	if !continuityHasContent(capsule) {
		return continuity.Capsule{}, false
	}
	capsule.ParentCapsule = source.Continuity.ID
	capsule.Format = continuity.FormatVersion
	capsule.ID = ""
	capsule.Source = continuity.SourceCompact
	capsule.BasisMessages = 0 // Session.AppendContinuity binds the fresh log.
	capsule.ParentSession = source.ID
	capsule.ParentMessages = len(source.Messages)
	capsule.Cleared = false
	return capsule, true
}

func continuityHasContent(c continuity.Capsule) bool {
	return c.Objective != "" || c.Phase != "" || c.Narrative != "" || c.NextAction != "" || c.StopCondition != "" ||
		len(c.Tasks) > 0 || len(c.Facts) > 0 || len(c.Decisions) > 0 || len(c.Rejected) > 0 || len(c.Files) > 0
}

func withoutContinuityOmission(omitted []string, field string) []string {
	kept := make([]string, 0, len(omitted))
	for _, name := range omitted {
		if name != field {
			kept = append(kept, name)
		}
	}
	return kept
}

// compactSettings is /compact auto and /compact at: the automatic-compaction
// posture, set from inside the TUI and persisted like every other setting.
// Anything else is guidance for a manual compaction and is not handled here.
func compactSettings(m *tuiModel, args string) (tea.Cmd, bool) {
	what, value, _ := strings.Cut(strings.TrimSpace(args), " ")
	value = strings.TrimSpace(value)
	cfg := m.app.config
	switch what {
	case "preview":
		// What compaction would do, before it does it: the conversation is
		// what a summary replaces, the frozen zone rides into the fresh
		// context unchanged, and the numbers are the estimator's own floor,
		// said as estimates. The decision this informs is compact-or-fork,
		// and it deserves the same visibility every other decision gets.
		state := m.app.loop.Session.State()
		if len(state.Messages) == 0 {
			return noticeCmd("", "nothing to compact yet"), true
		}
		conv := prefix.RequestTokens(provider.Request{Messages: state.Messages})
		sys := prefix.RequestTokens(provider.Request{System: m.app.loop.System})
		tools := prefix.RequestTokens(provider.Request{Tools: m.app.loop.Tools.Definitions()})
		summarizer, fromSlot, err := summarizerFor(m.app)
		if err != nil {
			return noticeCmd("error", err.Error()), true
		}
		who := "the active rung"
		if fromSlot {
			who = "the summarizer slot (" + summarizer.ID + ")"
		}
		var b strings.Builder
		fmt.Fprintf(&b, "compaction would summarize %d messages, ~%s conversation tokens, into a fresh context\n",
			len(state.Messages), compact(conv))
		fmt.Fprintf(&b, "system and tools (~%s) ride unchanged; %s writes the summary\n", compact(sys+tools), who)
		b.WriteString("the alternative is /fork, which keeps the full conversation and the warm prefix; /compact runs it")
		m.addInfo(b.String())
		return nil, true
	case "auto":
		switch value {
		case "":
			state := "on"
			if !cfg.CompactAuto {
				state = "off"
			}
			return noticeCmd("", "auto-compaction is "+state+", at "+itoa(compactThreshold(cfg))+"% of the window"), true
		case "on", "off":
			cfg.CompactAuto = value == "on"
			if err := cfg.Save(); err != nil {
				return noticeCmd("error", "saving the setting failed: "+err.Error()), true
			}
			return noticeCmd("", "auto-compaction is now "+value), true
		default:
			return noticeCmd("error", compactUsage), true
		}
	case "at":
		n, err := strconv.Atoi(value)
		if err != nil || n < 50 || n > 95 {
			return noticeCmd("error", compactUsage), true
		}
		cfg.CompactAtPercent = n
		if err := cfg.Save(); err != nil {
			return noticeCmd("error", "saving the threshold failed: "+err.Error()), true
		}
		return noticeCmd("", "auto-compaction now triggers at "+value+"% of the window"), true
	}
	return nil, false
}

func compactThreshold(cfg *config.Config) int {
	if cfg.CompactAtPercent == 0 {
		return 85
	}
	return cfg.CompactAtPercent
}

// summarize is a one-shot request outside the loop: no tools, no session
// append, just the conversation and an instruction to compress it.
func summarize(ctx context.Context, client provider.Provider, target provider.RouteTarget, messages []provider.Message, instructions string) (string, error) {
	text, _, _, err := summarizeRequestCall(ctx, client, target, summarizeRequest(messages, instructions))
	return text, err
}

func summarizeRequest(messages []provider.Message, instructions string) provider.Request {
	ask := "Summarize the conversation so far, per your instructions."
	if instructions != "" {
		ask += " Additional guidance from the user: " + instructions
	}
	return provider.Request{
		System:   []provider.Block{provider.Text{Text: compactSystem}},
		Messages: append(append([]provider.Message{}, messages...), provider.UserText(ask)),
	}
}

func summarizeRequestCall(ctx context.Context, client provider.Provider, target provider.RouteTarget, req provider.Request) (string, provider.Usage, bool, error) {
	stream, err := client.Stream(ctx, target, req)
	if err != nil {
		return "", provider.Usage{}, false, err
	}
	defer stream.Close()

	var b strings.Builder
	for {
		ev, err := stream.Next()
		if err != nil {
			return "", provider.Usage{}, false, err
		}
		switch ev.Type {
		case provider.EventTextDelta:
			b.WriteString(ev.Text)
		case provider.EventDone:
			if s := strings.TrimSpace(b.String()); s != "" {
				return s, ev.Usage, true, nil
			}
			return "", ev.Usage, true, fmt.Errorf("the model returned an empty summary")
		}
	}
}
